apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 02-service-management-web.yaml
  - 03-service-management-web-sidecar.yaml
  - 04-deployment-management-web.yaml
  - 05-deployment-management-web-sidecar.yaml
