export {
  DEFAULT_MESSAGE_BODY_MAX_LENGTH,
  EMAIL_MAX_LENGTH,
  PASSWORD_HASH_LENGTH,
  PASSWORD_MAX_LENGTH,
  SHORT_TEXT_MAX_LENGTH,
  TOKEN_HASH_HEX_LENGTH,
  VERIFICATION_TOKEN_KIND_MAX_LENGTH,
} from './field-lengths.js';
