apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - workloads.yaml
  - services.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: boilerplate-postgres-init
    files:
      - postgres-init/01_create_users.sh
      - postgres-init/02_init_management_db.sh
      - ../../../database/combined/init_database.sql
      - ../../../management-database/combined/init_management_database.sql
