version: 2
env_groups:
  db:
    vars:
      DB_HOST:
        default: "localhost"
      DB_PORT:
        default: "5433"
  valkey:
    valkey:
      vars:
        VALKEY_HOST:
          default: "localhost"
        VALKEY_PORT:
          default: "6380"
