apiVersion: v1
kind: Secret
metadata:
  name: boilerplate-local-placeholder
  namespace: boilerplate-local
type: Opaque
stringData:
  PLACEHOLDER: ENC[AES256_GCM,data:placeholder,iv:placeholder,tag:placeholder,type:str]
sops:
  age:
    - recipient: age1replacewithpublickey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        REPLACE_WITH_REAL_SOPS_OUTPUT
        -----END AGE ENCRYPTED FILE-----
  encrypted_regex: "^(data|stringData)$"
  version: 3.9.0
