apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: boilerplate-local
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: boilerplate
  source:
    repoURL: https://github.com/podverse/boilerplate.git
    targetRevision: feature/k8s-alpha
    path: infra/k8s/local/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: boilerplate-local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
