#!/bin/bash
set -e

: "${POSTGRES_READ_USER:?Missing POSTGRES_READ_USER}"
: "${POSTGRES_READ_WRITE_USER:?Missing POSTGRES_READ_WRITE_USER}"
: "${DB_READ_PASSWORD:?Missing DB_READ_PASSWORD}"
: "${DB_READ_WRITE_PASSWORD:?Missing DB_READ_WRITE_PASSWORD}"
: "${POSTGRES_DB:?Missing POSTGRES_DB}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_READ_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${POSTGRES_READ_USER}', '${DB_READ_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_READ_WRITE_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${POSTGRES_READ_WRITE_USER}', '${DB_READ_WRITE_PASSWORD}');
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_READ_USER}, ${POSTGRES_READ_WRITE_USER};
SQL
