#!/bin/bash
set -e

: "${POSTGRES_MANAGEMENT_READ_USER:?Missing POSTGRES_MANAGEMENT_READ_USER}"
: "${POSTGRES_MANAGEMENT_READ_WRITE_USER:?Missing POSTGRES_MANAGEMENT_READ_WRITE_USER}"
: "${POSTGRES_MANAGEMENT_READ_PASSWORD:?Missing POSTGRES_MANAGEMENT_READ_PASSWORD}"
: "${POSTGRES_MANAGEMENT_READ_WRITE_PASSWORD:?Missing POSTGRES_MANAGEMENT_READ_WRITE_PASSWORD}"

MANAGEMENT_DB_NAME="${POSTGRES_MANAGEMENT_DB:-${MANAGEMENT_DB_NAME:-boilerplate_management}}"

echo "Initializing management database: ${MANAGEMENT_DB_NAME}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d postgres <<SQL
SELECT 'CREATE DATABASE ${MANAGEMENT_DB_NAME}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${MANAGEMENT_DB_NAME}')\gexec
SQL

# Create management DB roles (per-DB users, not shared with app).
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d postgres <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_MANAGEMENT_READ_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${POSTGRES_MANAGEMENT_READ_USER}', '${POSTGRES_MANAGEMENT_READ_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_MANAGEMENT_READ_WRITE_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${POSTGRES_MANAGEMENT_READ_WRITE_USER}', '${POSTGRES_MANAGEMENT_READ_WRITE_PASSWORD}');
    END IF;
END
\$\$;
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" \
  -d "${MANAGEMENT_DB_NAME}" \
  -f /docker-entrypoint-initdb.d/init_management_database.sql

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "${MANAGEMENT_DB_NAME}" <<SQL
GRANT CONNECT ON DATABASE ${MANAGEMENT_DB_NAME} TO ${POSTGRES_MANAGEMENT_READ_USER}, ${POSTGRES_MANAGEMENT_READ_WRITE_USER};
GRANT USAGE ON SCHEMA public TO ${POSTGRES_MANAGEMENT_READ_USER}, ${POSTGRES_MANAGEMENT_READ_WRITE_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${POSTGRES_MANAGEMENT_READ_USER};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_MANAGEMENT_READ_USER};
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO ${POSTGRES_MANAGEMENT_READ_WRITE_USER};
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_MANAGEMENT_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${POSTGRES_MANAGEMENT_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${POSTGRES_MANAGEMENT_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO ${POSTGRES_MANAGEMENT_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO ${POSTGRES_MANAGEMENT_READ_WRITE_USER};
SQL
