#!/bin/bash
set -e

: "${DB_MANAGEMENT_READ_USER:?Missing DB_MANAGEMENT_READ_USER}"
: "${DB_MANAGEMENT_READ_WRITE_USER:?Missing DB_MANAGEMENT_READ_WRITE_USER}"
: "${DB_MANAGEMENT_READ_PASSWORD:?Missing DB_MANAGEMENT_READ_PASSWORD}"
: "${DB_MANAGEMENT_READ_WRITE_PASSWORD:?Missing DB_MANAGEMENT_READ_WRITE_PASSWORD}"

MANAGEMENT_DB_NAME="${DB_MANAGEMENT_NAME:-boilerplate_management}"
PG_SUPERUSER="${DB_USER:-${POSTGRES_USER:-user}}"

echo "Initializing management database: ${MANAGEMENT_DB_NAME}"

psql -v ON_ERROR_STOP=1 --username "$PG_SUPERUSER" -d postgres <<SQL
SELECT 'CREATE DATABASE ${MANAGEMENT_DB_NAME}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${MANAGEMENT_DB_NAME}')\gexec
SQL

# Create management DB roles (per-DB users, not shared with app).
psql -v ON_ERROR_STOP=1 --username "$PG_SUPERUSER" -d postgres <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_MANAGEMENT_READ_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_MANAGEMENT_READ_USER}', '${DB_MANAGEMENT_READ_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DB_MANAGEMENT_READ_WRITE_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${DB_MANAGEMENT_READ_WRITE_USER}', '${DB_MANAGEMENT_READ_WRITE_PASSWORD}');
    END IF;
END
\$\$;
SQL

psql -v ON_ERROR_STOP=1 --username "$PG_SUPERUSER" \
  -d "${MANAGEMENT_DB_NAME}" \
  -f /docker-entrypoint-initdb.d/init_management_database.sql

psql -v ON_ERROR_STOP=1 --username "$PG_SUPERUSER" -d "${MANAGEMENT_DB_NAME}" <<SQL
GRANT CONNECT ON DATABASE ${MANAGEMENT_DB_NAME} TO ${DB_MANAGEMENT_READ_USER}, ${DB_MANAGEMENT_READ_WRITE_USER};
GRANT USAGE ON SCHEMA public TO ${DB_MANAGEMENT_READ_USER}, ${DB_MANAGEMENT_READ_WRITE_USER};
GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${DB_MANAGEMENT_READ_USER};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${DB_MANAGEMENT_READ_USER};
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO ${DB_MANAGEMENT_READ_WRITE_USER};
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${DB_MANAGEMENT_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${DB_MANAGEMENT_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${DB_MANAGEMENT_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO ${DB_MANAGEMENT_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO ${DB_MANAGEMENT_READ_WRITE_USER};
SQL
