#!/bin/bash
set -e

MANAGEMENT_DB_NAME="${MANAGEMENT_DB_NAME:-boilerplate_management}"

echo "Initializing management database: ${MANAGEMENT_DB_NAME}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d postgres <<SQL
SELECT 'CREATE DATABASE ${MANAGEMENT_DB_NAME}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${MANAGEMENT_DB_NAME}')\gexec
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" \
  -d "${MANAGEMENT_DB_NAME}" \
  -f /docker-entrypoint-initdb.d/init_management_database.sql

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" -d "${MANAGEMENT_DB_NAME}" <<SQL
GRANT CONNECT ON DATABASE ${MANAGEMENT_DB_NAME} TO read, read_write;
GRANT USAGE ON SCHEMA public TO read, read_write;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO read;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO read;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO read_write;
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO read_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO read;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO read;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON TABLES TO read_write;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO read_write;
SQL
