#!/bin/bash
# Creates app DB read-only and read-write users (names from POSTGRES_READ_USER, POSTGRES_READ_WRITE_USER).
# Runs first in docker-entrypoint-initdb.d/ so ALTER DEFAULT PRIVILEGES apply to tables created by init_database.sql.
set -e

: "${POSTGRES_READ_USER:?Missing POSTGRES_READ_USER}"
: "${POSTGRES_READ_WRITE_USER:?Missing POSTGRES_READ_WRITE_USER}"
: "${DB_READ_PASSWORD:?Missing DB_READ_PASSWORD}"
: "${DB_READ_WRITE_PASSWORD:?Missing DB_READ_WRITE_PASSWORD}"
: "${POSTGRES_DB:?Missing POSTGRES_DB}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_READ_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${POSTGRES_READ_USER}', '${DB_READ_PASSWORD}');
    END IF;
END
\$\$;

DO \$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${POSTGRES_READ_WRITE_USER}') THEN
        EXECUTE format('CREATE USER %I WITH PASSWORD %L', '${POSTGRES_READ_WRITE_USER}', '${DB_READ_WRITE_PASSWORD}');
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${POSTGRES_READ_USER}, ${POSTGRES_READ_WRITE_USER};
GRANT USAGE ON SCHEMA public TO ${POSTGRES_READ_USER}, ${POSTGRES_READ_WRITE_USER};

GRANT SELECT ON ALL TABLES IN SCHEMA public TO ${POSTGRES_READ_USER};
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_READ_USER};

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${POSTGRES_READ_WRITE_USER};
GRANT SELECT, USAGE, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ${POSTGRES_READ_WRITE_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO ${POSTGRES_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON SEQUENCES TO ${POSTGRES_READ_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${POSTGRES_READ_WRITE_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, USAGE, UPDATE ON SEQUENCES TO ${POSTGRES_READ_WRITE_USER};
SQL
